kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/caishu/myphp.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: build.groovy 
